### ISSUE TITLE
first step towards EO testing in CI

### ISSUE THREAD

**Issue by dours** [polystat/py2eo#10]
https://github.com/polystat/py2eo/blob/master/python/python3/test/eo/map-tests.eo is a test for  https://github.com/polystat/py2eo/blob/master/python/python3/eo/map.eo . It should pass the same way the tests of eo-runtime in cqfn/eo pass . Please, run this test as a CI action. 
Currently https://github.com/cqfn/eo/commit/5c475254033b64fb650eb0104701d3ad00fefd1e this branch should be ok. But maybe also the HEAD of master. Maybe running both variants is also reasonable...

**Comment by dours** [comment]
@PetrB09   beware, map.eo uses sandbox/hse

**Comment by PetrB09** [comment]
set up runEO phase in CI, but it is not working: https://github.com/PetrB09/py2eo/runs/4141503107?check_suite_focus=true

**Comment by tdv42** [comment]
to be fixed after merge, see https://github.com/polystat/py2eo/issues/5#issuecomment-963383982

**Comment by dours** [comment]
@PetrB09  please, try again

**Comment by PetrB09** [comment]
Maven can't find jupiter dependency https://github.com/PetrB09/py2eo/runs/4171277870?check_suite_focus=true

**Comment by PetrB09** [comment]
Setup in #44
