### ISSUE TITLE
Support for dynamic object attributes

### ISSUE THREAD

**Issue by bugdea1er** [polystat/py2eo#12]
- Realise a pass which replaces all calls to the object attributes with `getattr`, or `setattr`
- All calls to `getattr` and `setattr` replace with custom functions which will use map for storing object's attributes. Use python's map for now, consider using eolang's map in the future.

**Comment by bugdea1er** [comment]
* Each object shall have `__dict__` attribute which is implemented via EOmap. It maps attribute names to their value.
* Implementation of `getattr` shall use `EOmap.find` attribute
* Implementation of `setattr` shall use `EOmap.add` attribute

**Comment by bugdea1er** [comment]
Attribute references with operator `.` replaced with custom implementation of `getattr` in pr#33

**Comment by dours** [comment]
We decided not to implement this because the generated EO would be very hard to statically check.
