### ISSUE TITLE
Consider mutations for validator

### ISSUE THREAD

**Issue by tdv42** [polystat/py2eo#126]
- [x] Variable identifier
- [ ] System variable identifier https://github.com/polystat/py2eo/blob/24ca8007e10f15519953ecbb579926b73e157f01/src/test/resources/org/polystat/py2eo/testParserPrinter/test_abc.yaml#L46
- [ ] Classname identifier https://github.com/polystat/py2eo/blob/24ca8007e10f15519953ecbb579926b73e157f01/src/test/resources/org/polystat/py2eo/testParserPrinter/test_abc.yaml#L48
- [x] Remove brackets https://github.com/polystat/py2eo/blob/24ca8007e10f15519953ecbb579926b73e157f01/src/test/resources/org/polystat/py2eo/testParserPrinter/test_abc.yaml#L51
- [x] `False` -> `false` https://github.com/polystat/py2eo/blob/24ca8007e10f15519953ecbb579926b73e157f01/src/test/resources/org/polystat/py2eo/testParserPrinter/test_abc.yaml#L60
- [x] Mutate `int` value
- [ ] Add some classname that doesn't exist https://github.com/polystat/py2eo/blob/24ca8007e10f15519953ecbb579926b73e157f01/src/test/resources/org/polystat/py2eo/testParserPrinter/test_aifc.yaml#L12
- [ ] Mutate `string` value  https://github.com/polystat/py2eo/blob/24ca8007e10f15519953ecbb579926b73e157f01/src/test/resources/org/polystat/py2eo/testParserPrinter/test_aifc.yaml#L28
- [ ] Add excess param https://github.com/polystat/py2eo/blob/24ca8007e10f15519953ecbb579926b73e157f01/src/test/resources/org/polystat/py2eo/testParserPrinter/test_aifc.yaml#L168
- [x] `Def` -> `df` https://github.com/polystat/py2eo/blob/24ca8007e10f15519953ecbb579926b73e157f01/src/test/resources/org/polystat/py2eo/testParserPrinter/test_aifc.yaml#L185
- [ ] Swap `string` values https://github.com/polystat/py2eo/blob/24ca8007e10f15519953ecbb579926b73e157f01/src/test/resources/org/polystat/py2eo/testParserPrinter/test_aifc.yaml#L211
- [ ] Remove `string` https://github.com/polystat/py2eo/blob/24ca8007e10f15519953ecbb579926b73e157f01/src/test/resources/org/polystat/py2eo/testParserPrinter/test_aifc.yaml#L212
- [ ] Swap params in list https://github.com/polystat/py2eo/blob/24ca8007e10f15519953ecbb579926b73e157f01/src/test/resources/org/polystat/py2eo/testParserPrinter/test_aifc.yaml#L214
- [ ] Swap functions call in chain
- [x] Swap `+` for `-`, `*` -> `/`
- [ ] `>>` -> `<<`
- [ ] Mutate logic operations
- [ ] `+=` -> `-=`
- [ ] Remove method
- [ ] Swap code in `ifelse` sections
- [ ] Remove one of `except`
- [x] `True` -> `False`
- [ ] Remove `async`
- [ ] `yield from` -> `return`
- [ ] Some mutation for `exec`
- [x] Swap `break` with `continue`

**Comment by bugdea1er** [comment]
Checker module migrated to a separate repository
