### ISSUE TITLE
Set up Py2EO translation delivery to Maven Central

### ISSUE THREAD

**Issue by tdv42** [polystat/py2eo#16]
GroupID: org.polystat
ArtifactID: py2eo
Licence: MIT

**Comment by PetrB09** [comment]
I found this guide: https://central.sonatype.org/publish/publish-guide/ As far as I know, Py2EO is a subproject, do I need to create a new account for new repo?

**Comment by yegor256** [comment]
@PetrB09 I would recommend you to copy the deployment mechanism from [cqfn/eo](https://github.com/cqfn/eo). You will need `.rultor.yml` file and make sure your `pom.xml` has `jcabi.com:jcabi-parent` as a parent.

**Comment by PetrB09** [comment]
I got acquainted with the deployment mechanism, but the question with the account and the group remained: do I need a separate account on the maven central for deploying to the Polistat group or you can give (or create) an account for us?

**Comment by yegor256** [comment]
@PetrB09 every time you post a message in GitHub, start it with the name of the person, like I'm doing. Otherwise, it's not clear who you are talking to and your message doesn't land to my inbox.

**Comment by yegor256** [comment]
@PetrB09 you don't need a new account, you use the existing one and deploy to `org.polystat` group

**Comment by PetrB09** [comment]
@rultor release, tag is 0.0.1

**Comment by PetrB09** [comment]
@rultor release, tag is `0.0.1`

**Comment by PetrB09** [comment]
@rultor deploy

**Comment by PetrB09** [comment]
@rultor release, tag is `0.0.1`

**Comment by PetrB09** [comment]
@rultor release, tag is `0.0.1`

**Comment by PetrB09** [comment]
@rultor deploy

**Comment by dours** [comment]
let's check the third time
@rultor deploy

**Comment by PetrB09** [comment]
@rultor release, tag is `0.0.1`

**Comment by PetrB09** [comment]
@rultor release, tag is `0.0.1`

**Comment by PetrB09** [comment]
@yegor256 Could you please explain which profiles needs to use? I tried to use `polystat` and without it

**Comment by yegor256** [comment]
@PetrB09 you need this, I believe: https://github.com/polystat/polystat/blob/master/pom.xml#L96-L103

**Comment by PetrB09** [comment]
@rultor release, tag is `0.0.1`

**Comment by PetrB09** [comment]
@rultor release, tag is `0.0.1`

**Comment by PetrB09** [comment]
@dours can you give access rultor for next releases?

**Comment by dours** [comment]
@PetrB09 I don't think I can give access to rultor. I think, only @yegor256  can

**Comment by yegor256** [comment]
@PetrB09 done! BTW, your version is released: https://repo.maven.apache.org/maven2/org/polystat/py2eo/ You can try to release 0.0.2 now, to make sure the release cycle works perfectly till the end.

**Comment by tdv42** [comment]
@rultor release, tag is `0.0.2`

**Comment by yegor256** [comment]
@PetrB09 now you have it: https://github.com/polystat/py2eo/releases congrats!
