### ISSUE TITLE
Add CI for counting passed tests (even disabled)

### ISSUE THREAD

**Issue by bugdea1er** [polystat/py2eo#192]

**Comment by AndrewG0R** [comment]
Add counting passed tests in CI via maven with numeric representation of all tests which can be transpiled or not. 

My idea:
run single test in tests class and disable CI failing after tranpilation failure.

**Comment by AndrewG0R** [comment]
Right now we have in [branch](https://github.com/AndrewG0R/py2eo/tree/counter) counter test which will fail in case of failure. We have only to add handling profiles in pom.xml for maven builder

**Comment by AndrewG0R** [comment]
[CI](https://github.com/AndrewG0R/py2eo/actions/runs/2156517305) in fork failed with file not found exception

**Comment by PetrB09** [comment]
Want to split test to 2 groups:
- enabled - with assertations
- disabled - with assume and do not failure CI
Needs separate test source and test methods

**Comment by AndrewG0R** [comment]
[CI](https://github.com/AndrewG0R/py2eo/runs/6194625076?check_suite_focus=true) failed with error:
ls: cannot access './target/eo-test/04-pull/org/eolang/': No such file or directory

but tests for [counter stage](https://github.com/AndrewG0R/py2eo/runs/6194037148?check_suite_focus=true) was completed and didn't fail this stage:

**Comment by AndrewG0R** [comment]
Right now CI works well, added stage which run all tests even desabled and in the end of this stage we can see how many test failed. The stage results have to be validated by @bugdea1er for better understadning what we need to fix. All stage results are available [here](https://github.com/AndrewG0R/py2eo/runs/6208533557?check_suite_focus=true).
