### ISSUE TITLE
Determine full set of test cases

### ISSUE THREAD

**Issue by tdv42** [polystat/py2eo#20]

**Comment by AndrewG0R** [comment]
Right now we have such tests groups:
- while -> `src/test/resources/org/polystat/py2eo/simple_tests/whileCheck`
- if -> `src/test/resources/org/polystat/py2eo/simple_tests/ifCheck` - checking simple constructions with if 
- assignment -> `src/test/resources/org/polystat/py2eo/simple_tests/assignCheck`
- cpython tests - tests based on cpython tests with changing etalon line for test execution checking

**Comment by AndrewG0R** [comment]
Is available here - https://github.com/polystat/py2eo/wiki/Tests-Structure
