### ISSUE TITLE
Implement simple main method in tests

### ISSUE THREAD

**Issue by PetrB09** [polystat/py2eo#212]
Implements simple public static void main(String[] args) method for selectively run tests

**Comment by AndrewG0R** [comment]
Right now as I see it is possible to run single method after running full pack of tests, especially for simple tests suite. During running of these test suites we have such output:

![image](https://user-images.githubusercontent.com/69813637/163138566-6b669ee2-20ca-4876-9eee-cef97b8a7d73.png)

the main problem is that we can't predefine parameter for parametrized test. But we can re-run one test like it is shown below:

![image](https://user-images.githubusercontent.com/69813637/163138913-8a8ebc83-d2eb-4047-b648-306a8a8ded18.png)

for running the N-th test you will need to press right btn on the PC mouse on the desired test runner from the array. 

The another way of running single test is to change parametrization processor with setting some more complex file filter like it is shown below:
```
Files.walk(simpleTestsFolder.toPath).filter((p: Path) => p.toString.endsWith(".yaml") && p.toString.contains("assign")).forEach((p: Path) => {
      val testHolder = new File(p.toString)
     ...
    })
```

the code scope above can run all tests for `assign` construction. You can also set direct name of file for minimizing.

 The final solution for single test runner is to create tests holder with setting direct path to the file with desired language construction and run it directly via one test.
