### ISSUE TITLE
Refactor CPython tests for using as python code for translator test

### ISSUE THREAD

**Issue by PetrB09** [polystat/py2eo#22]
We want to use [CPython tests](https://github.com/python/cpython/blob/main/Lib/test) as code base for testing translator. Next tests may be used for this:
 - [ ] test_asyncgen.py
- [ ] test_decorators.py
- [ ] test_keyword.py
- [ ] test_string_literals.py
- [ ] test_tracemalloc.py
- [ ] test_unary.py
- [ ] test_asynchat.py
- [ ] test_exception_hierarchy.py
- [ ] test_positional_only_arg.py
- [ ] test_string.py
- [ ] test_trace.py
- [ ] test_weakref.py
- [ ] test_asyncore.py
- [ ] test_exceptions.py
- [ ] test_property.py
- [ ] test_structmembers.py
- [ ] test_tuple.py
- [ ] test_weakset.py
- [ ] test_augassign.py
- [ ] test_exception_variations.py
- [ ] test.py
- [ ] test_struct.py
- [ ] test_type_annotations.py
- [ ] test_with.py
- [ ] test_baseexception.py
- [ ] test_grammar.py
- [ ] test_raise.py
- [ ] test_structseq.py
- [ ] test_typechecks.py
- [ ] test_yield_from.py
- [ ] test_binop.py
- [ ] test_interpreters.py
- [ ] test_range.py
- [ ] test_subclassinit.py
- [ ] test_type_comments.py
- [ ] test_bool.py
- [ ] test_isinstance.py
- [ ] test_scope.py
- [ ] test_syntax.py
- [ ] test_types.py
- [ ] test_class.py
- [ ] test_keywordonlyarg.py
- [ ] test_slice.py
- [ ] test_traceback.py
- [ ] test_typing.py

**Comment by AndrewG0R** [comment]
We can right now parse `assertEqual` and `equal` with building .txt file with parsing results which will contain function parameters

**Comment by AndrewG0R** [comment]
Added own .py pre-processor with handling assertEquals params. Redirection of output to the .txt file with CPythonTest names. Right now bug fix for more efficient working.

**Comment by AndrewG0R** [comment]
@dours right now we have several files of CPython test which can be used for translator testing, but where I can place it in this repo? Or I will have to create a new repo for this pre-processor and its results?

**Comment by dours** [comment]
Plans for support of cpython tests are suspended after the last status call. It looks like we are not going to support many small python features, which will block our ability to run the original tests.

**Comment by dours** [comment]
#48 adds the FindBadConstructs analysis, which looks for `eval` calls in the cpython tests. We may also look for other patterns with this pass

**Comment by dours** [comment]
too hard if only a subset of python is supported. We implemented our own test instead (#21)
