### ISSUE TITLE
Start testing the translator through CPython tests

### ISSUE THREAD

**Issue by PetrB09** [polystat/py2eo#23]
- [x] Find the most simple tests from #22 
- [x] Remove unsupported instructions 
- [x] Create test case in Tests.scala
- [x] Check test output in EO

**Comment by AndrewG0R** [comment]
Current progress and results:
* exploring test initialization in Scala
* working with current assertion in `immutabilization` test
* fixed crash before test assert

**Comment by AndrewG0R** [comment]
@PetrB09 what did you mean with point - `remove unsupported instructions`. Is it connected with the most simple test from mentioned ticket or removing such instructions from the current repository version?

**Comment by AndrewG0R** [comment]
For testing was selected [this test](https://github.com/python/cpython/blob/main/Lib/test/test_slice.py)

**Comment by AndrewG0R** [comment]
Current status:
* added test with translator usage
* added .py file for testing which contains all supported constructions
* small refactoring of existing test for immutabialization

more info is in [the commit](https://github.com/AndrewG0R/py2eo/commit/162b9fb8ec8ed68a48508f09412edeed1cdd472e)

**Comment by dours** [comment]
see #22

**Comment by dours** [comment]
#49  tests parser and printer with 364 of the cpython tests
