### ISSUE TITLE
Launch checker in multiple threads

### ISSUE THREAD

**Issue by bugdea1er** [polystat/py2eo#230]
Tests transpilation in checker now can be run in parallel, need to use `Future` or `Promise` for it.

**Comment by bugdea1er** [comment]
`TestResults` class should contain `Future` value in the map instead of `CompilingResult`:
https://github.com/polystat/py2eo/blob/6a06637ceb9c4902722f1e8e707ccb748c43e6eb/checker/src/main/scala/org/polystat/py2eo/checker/TestResult.scala#L14

`Write` object should wait for these values before writing:
https://github.com/polystat/py2eo/blob/6a06637ceb9c4902722f1e8e707ccb748c43e6eb/checker/src/main/scala/org/polystat/py2eo/checker/Write.scala#L73

`Check` object should launch tests in parallel:
https://github.com/polystat/py2eo/blob/6a06637ceb9c4902722f1e8e707ccb748c43e6eb/checker/src/main/scala/org/polystat/py2eo/checker/Check.scala#L38

and place resulting functions properly here:
https://github.com/polystat/py2eo/blob/6a06637ceb9c4902722f1e8e707ccb748c43e6eb/checker/src/main/scala/org/polystat/py2eo/checker/Check.scala#L55

**Comment by AndrewG0R** [comment]
How to run my code for checking results? Or it will be available only via CI?
