### ISSUE TITLE
Migrate to Abstract Syntax Trees Generator in mutator

### ISSUE THREAD

**Issue by bugdea1er** [polystat/py2eo#242]
Use https://github.com/unified-ast/ast-generator tool in mutator

**Comment by tdv42** [comment]
after https://github.com/cqfn/astranaut/issues/52 is resolved

**Comment by bugdea1er** [comment]
Waiting for https://github.com/cqfn/astranaut/issues/61

**Comment by tdv42** [comment]
> Waiting for [cqfn/astranaut#61](https://github.com/cqfn/astranaut/issues/61)

Resolved for now

**Comment by bugdea1er** [comment]
API Guide: https://github.com/cqfn/astranaut/blob/master/src/main/documents/api.md

**Comment by tdv42** [comment]
next steps:
1. Implement converter ASTG tree to AST
2. Migrate existing migrations to ASTG
3. Add more migrations

**Comment by tdv42** [comment]
Suggested implement syntax for specifying a specific occurrence of a node in a transformation rule: https://github.com/cqfn/astranaut/issues/71

**Comment by tdv42** [comment]
Waiting for https://github.com/cqfn/astranaut/issues/81

**Comment by bugdea1er** [comment]
Checker module migrated to a separate repository
