### ISSUE TITLE
Update in README the link to the latest stable release

### ISSUE THREAD

**Issue by br4ch1st0chr0n3** [polystat/py2eo#262]
Hi! On Ubuntu 20.04, I found out that the [link](https://repo1.maven.org/maven2/org/polystat/py2eo/0.0.4/py2eo-0.0.4-jar-with-dependencies.jar) to the transpiler's `*.jar` file in [README](https://github.com/polystat/py2eo#how-to-use-it) is outdated. So, I decided to run the freshest [version](https://repo1.maven.org/maven2/org/polystat/py2eo/0.0.11.2/py2eo-0.0.11.2-jar-with-dependencies.jar) from [here](https://repo1.maven.org/maven2/org/polystat/py2eo/0.0.11.2/). Unfortunately, I received:
```sh
Error: Could not find or load main class org.polystat.py2eo.transpiler.Main
Caused by: java.lang.ClassNotFoundException: org.polystat.py2eo.transpiler.Main
```
Here were my steps:

1. Create a file `test.py` in `./dir`:
```py
def myC():
    class c:
        value = 11
        def getValue(self): return self.value
    class d(c): pass
    o = d()
    return o.getValue() == 11
```
1. Download the transpiler into `./dir`
1. Run `.jar` in `./dir` 
```sh
cd dir
java -jar py2eo*.jar test.py
```

Please, make the link refer to the latest stable version of the transpiler.

**Comment by dours** [comment]
@br4ch1st0chr0n3  Hi! I've updated the link to this one: https://repo1.maven.org/maven2/org/polystat/py2eo/transpiler/0.0.11.3/transpiler-0.0.11.3-jar-with-dependencies.jar

**Comment by br4ch1st0chr0n3** [comment]
Thank you!
