### ISSUE TITLE
Implement basic inheritance (without metaclasses) as a python to python pass

### ISSUE THREAD

**Issue by dours** [polystat/py2eo#27]
i.e., generate python code with classes, but each class must not inherit anything. The `__bases__` attribute and MRO https://www.python.org/download/releases/2.3/mro/ must also be implemented explicitly.

**Comment by bugdea1er** [comment]
* Each object shall have `__bases__` attribute which is implemented via EOarray. It contains all parent object in order of inheritance.
* MRO will search in the instance class for the invoked attribute. If not found, it goes into the first parents, if there is also not found. It will look into the parent of the parent. This will continue till the end of inheriting classes.
