### ISSUE TITLE
Add tests for doc examples from readme

### ISSUE THREAD

**Issue by tdv42** [polystat/py2eo#273]
After #270

**Comment by AndrewG0R** [comment]
[While](https://github.com/polystat/py2eo#82-while) - [test](https://github.com/polystat/py2eo/blob/doc_tests/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/while/while_doc_1.yaml), [test](https://github.com/polystat/py2eo/blob/doc_tests/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/while/while_doc_2.yaml)


[For](https://github.com/polystat/py2eo#83-for) - [test](https://github.com/polystat/py2eo/blob/doc_tests/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/for/for_doc_1.yaml), [test](https://github.com/polystat/py2eo/blob/doc_tests/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/for/for_doc_2.yaml)

[Assign](https://github.com/polystat/py2eo#72-assignment-statements) - [test](https://github.com/polystat/py2eo/blob/doc_tests/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/assign/assign_doc.yaml)

[If-elif-else](https://github.com/polystat/py2eo#81-if-elif-else) - [test](https://github.com/polystat/py2eo/blob/doc_tests/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/if/if_doc_1.yaml), [test](https://github.com/polystat/py2eo/blob/doc_tests/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/if/if_doc_2yaml)
