### ISSUE TITLE
Pass break tests

### ISSUE THREAD

**Issue by AndrewG0R** [polystat/py2eo#325]
[for_break.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/break/for_break.yaml)

[for_try_else_break.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/break/for_try_else_break.yaml)

[nested_for_break1.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/break/nested_for_break1.yaml)

[nested_for_break2.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/break/nested_for_break2.yaml)

[nested_for_break3.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/break/nested_for_break3.yaml)

[nested_for_break_else.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/break/nested_for_break_else.yaml)

[while_try_except_else.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/break/while_try_except_else.yaml)

**Comment by dours** [comment]
[for_break.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/break/for_break.yaml)   done in #355 

[while_try_except_else.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/break/while_try_except_else.yaml)  done in #357
