### ISSUE TITLE
Pass continue tests

### ISSUE THREAD

**Issue by AndrewG0R** [polystat/py2eo#326]
[for_break_continue_nested.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/continue/for_break_continue_nested.yaml)

[for_continue.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/continue/for_continue.yaml)

[for_continue_nested.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/continue/for_continue_nested.yaml)

[for_try_else_continue1.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/continue/for_try_else_continue1.yaml)

[for_try_else_continue2.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/continue/for_try_else_continue2.yaml)

[while_try_except_finally.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/continue/while_try_except_finally.yaml)

**Comment by dours** [comment]
for_continue,  [for_try_else_continue2.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/continue/for_try_else_continue2.yaml) done in #355 

[while_try_except_finally.yaml](https://github.com/polystat/py2eo/commit/198acdab10e65eb59689c6993a5d671eaa5c0426#diff-a24c56a942cef2e98cabb833f58d295cbaf6faf8096ef3b6bdbf60af94e3d6f3) done in #357

**Comment by dours** [comment]
done in #377
