### ISSUE TITLE
Pass expression statements tests

### ISSUE THREAD

**Issue by AndrewG0R** [polystat/py2eo#327]
[expression-statement-1.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/expression-statement/expression-statement-1.yaml)

[expression-statement-2.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/simple-statements/expression-statement/expression-statement-2.yaml)

**Comment by dours** [comment]
#362
