### ISSUE TITLE
Pass try tests

### ISSUE THREAD

**Issue by AndrewG0R** [polystat/py2eo#331]
[exceptions-finally-3.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/compound-statements/try/exceptions-finally-3.yaml)

**Comment by dours** [comment]
#371

**Comment by 0pdd** [comment]
@AndrewG0R 3 puzzles [#399](https://github.com/polystat/py2eo/issues/399), [#400](https://github.com/polystat/py2eo/issues/400), [#401](https://github.com/polystat/py2eo/issues/401) are still not solved.
