### ISSUE TITLE
Pass arithmetic conversion tests

### ISSUE THREAD

**Issue by AndrewG0R** [polystat/py2eo#333]
[conversion-18.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/expressions/arithmetic-conversions/conversion-18.yaml)

[conversion-12.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/expressions/arithmetic-conversions/conversion-12.yaml)

**Comment by dours** [comment]
done in #357
