### ISSUE TITLE
Pass attribute reference tests

### ISSUE THREAD

**Issue by AndrewG0R** [polystat/py2eo#334]
[attribute-1.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/expressions/attribute-reference/attribute-1.yaml)

**Comment by dours** [comment]
The attribute-1 was removed because it dynamically creates variables in the class constructor, while the variables are not declared in the class itself. We do not support this, so attribute-1 is removed. All other attribute tests pass already
