### ISSUE TITLE
Pass comparisons tests

### ISSUE THREAD

**Issue by AndrewG0R** [polystat/py2eo#335]
[comparison-3.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/expressions/comparisons/comparison-3.yaml)

[comparison-5.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/expressions/comparisons/comparison-5.yaml)

[comparison-6.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/expressions/comparisons/comparison-6.yaml)

[comparison-7.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/expressions/comparisons/comparison-7.yaml)

**Comment by dours** [comment]
comparison-3 is also enabled for some time now.

**Comment by dours** [comment]
no disabled comparison tests left
