### ISSUE TITLE
Tests for inheritance resolution

### ISSUE THREAD

**Issue by bugdea1er** [polystat/py2eo#34]
Create tests for custom method resolution order for non-trivial class architectures.
These tests should contain:
- attribute references
- functions `setattr` and `getattr`
- dynamic creation and deletion of attributes 

Note that some inheritance schemes throw exceptions, need to test that too.

**Comment by AndrewG0R** [comment]
can you clarify please what did you mean with custom method resolution order and non-tivial architectures? I think I know trivial class architectures.

**Comment by AndrewG0R** [comment]
added initial test functionality for inheritance [here](https://github.com/AndrewG0R/py2eo/commit/256f086ebfe9200c0915b8950a17b0c494e5dd4d)
