### ISSUE TITLE
Pass lambda tests

### ISSUE THREAD

**Issue by AndrewG0R** [polystat/py2eo#340]
[lambda2.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/expressions/lambda/lambda2.yaml)

[lambda3.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/expressions/lambda/lambda3.yaml)

**Comment by dours** [comment]
#370

**Comment by 0pdd** [comment]
@AndrewG0R the puzzle [#403](https://github.com/polystat/py2eo/issues/403) is still not solved.
