### ISSUE TITLE
Pass lists displays

### ISSUE THREAD

**Issue by AndrewG0R** [polystat/py2eo#341]
[generator-display.yaml](https://github.com/polystat/py2eo/blob/master/transpiler/src/test/resources/org/polystat/py2eo/transpiler/simple-tests/expressions/list-displays/list-generator-display.yaml)

**Comment by tdv42** [comment]
related to https://github.com/polystat/py2eo/issues/319

**Comment by dours** [comment]
generator-display is removed because generators are not supported by us
