### ISSUE TITLE
Try checker on CPython and django again

### ISSUE THREAD

**Issue by bugdea1er** [polystat/py2eo#350]
Transpiler may now work differently

**Comment by bugdea1er** [comment]
No differences for cpython tests since the latest try

**Comment by tdv42** [comment]
Try it now on Django

**Comment by bugdea1er** [comment]
The newly obtained django checker results are not much different from the previous ones already in the django-results branch.  So far, we are hoping for the correct sorting of tests instead of sorting the tests ourselves by the text of the test and mutations, so it is not possible to point out a specific error on such a set.

**Comment by tdv42** [comment]
done
