### ISSUE TITLE
Implement dummy objects for full python compilation

### ISSUE THREAD

**Issue by bugdea1er** [polystat/py2eo#37]
Implement dummy objects for every python's AST node for possible compilation of specified language's subset. These object are not required to be fully functional, compiler's output should be grammatically correct. For example, python's `for` statement can be translated to this object:
```
[ target_list expression_list suite ] > ForStmt
```

**Comment by dours** [comment]
Partial success: a file test_typing.py (5k lines) is translated to test_typing.eo. The .eo file does not fail to parse, but it currently has 232 undefined identifiers, so it is not compilable to java. See brach mutableCage

**Comment by dours** [comment]
Current status: this generator works for all of our subset of cpython tests, ***but some generated EO fails to parse (mostly because of problems with string/float literals)***.

**Comment by dours** [comment]
Done in #102
