### ISSUE TITLE
immutable map in EO

### ISSUE THREAD

**Issue by dours** [polystat/py2eo#4]
implement the simplest possible immutable map, which maps strings to EO objects. 
Speaking it terms of scala, we need something like
abstract class eomap() {
  // (no exceptions!) 
  def find(key : String) : Option[Object]
  // if the key already exists in the map then remove it 
  def add(key : String, value : Object) : eomap
  def remove(key : String) : eomap
}

Use the most simple linear implementaiton (presumably, with arrays). 

See https://github.com/cqfn/eo/tree/master/sandbox/hse/eo before coding, maybe it is at least partially done there

**Comment by bugdea1er** [comment]
Implementing Scala's Option[Object] with object of two attributes: .valid and .value. First attribute is set to true if the value is found.
