### ISSUE TITLE
Implement simple python classes (according to sec. 2.1.1 in the overleaf Py2EO Mapping document)

### ISSUE THREAD

**Issue by dours** [polystat/py2eo#47]

**Comment by dours** [comment]
Development is in https://github.com/polystat/py2eo/tree/hackCage .  It is currently blocked by https://github.com/cqfn/eo/issues/508 (a test with a `while` loop cannot compile because of this problem) . Fixing https://github.com/cqfn/eo/issues/512 instead of 508 may also help, but I think that fixing cqfn/eo#508 is easier.

**Comment by dours** [comment]
first version is implemented in  #68

**Comment by 0pdd** [comment]
@dours the puzzle [#402](https://github.com/polystat/py2eo/issues/402) is still not solved.
