### ISSUE TITLE
Add arithmetics support

### ISSUE THREAD

**Issue by bugdea1er** [polystat/py2eo#65]
- Implement objects `pyInt` and `pyFloat` as eo objects for supporting intertype arithmetics (e.g. `5 + 6.7`)
- Implement build of `pyInt.eo` and `pyFloat.eo` separately and link them via `+package`

**Comment by bugdea1er** [comment]
Objects `pyInt` and `pyFloat` implemented but still no success with linking them to eolang result code

**Comment by dours** [comment]
Partially done with the help of #63  #280, #282 + see a newer issue #265
