### ISSUE TITLE
Fix styleChecker errors

### ISSUE THREAD

**Issue by PetrB09** [polystat/py2eo#77]
Needs to fix stylechecker errors in CI https://github.com/PetrB09/py2eo/runs/4645491194?check_suite_focus=true

**Comment by AndrewG0R** [comment]
The latest supported by stylecheker Scala version is 2.12 which is incompatible with current project Scala version. More info can be found on the official feature [web page](http://www.scalastyle.org/).

**Comment by dours** [comment]
@AndrewG0R  even more info can be found here https://github.com/scalastyle/scalastyle/issues/360 . The stylechecker for scala 2.13 is here https://scalastyle.beautiful-scala.com/

**Comment by dours** [comment]
many fixes are done in #83

**Comment by tdv42** [comment]
see https://github.com/polystat/py2eo/pull/118
