### ISSUE TITLE
Fix parsing and handling command line arguments

### ISSUE THREAD

**Issue by AndrewG0R** [polystat/py2eo#78]

**Comment by PetrB09** [comment]
Needs to add parsing first command line argument: path to input python file. Also needs to handle incorrect argument and show error message

**Comment by dours** [comment]
I'm expecting this in PR #82

**Comment by PetrB09** [comment]
It will be nice to get other params such as "-o" - output files. @dours, which other params we needs too?

**Comment by dours** [comment]
@PetrB09  `--version`, `--debug` to turn on/off debug printers.
